version: '3.9'

services:
# Сервис для разворачивания контейнера с базой данных
  db:
    pull_policy: missing
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=S3cur3P@ssW0rd!

# Сервис для разворачивания контейнера с приложением
  webapi:
    image: webapi
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - db
    build:
      context: ./
      dockerfile: Dockerfile

# Сервис для разворачивания контейнера с автотестами
  tests: 
    image: mrexpen/planet_olymp_phase1
    pull_policy: always
    ports:
      - "8090:8080"
    depends_on:
      - webapi
    environment:
      SERVER_URL: http://webapi:80
      STAGE: all
      # all - запуск всех тестов из трёх доступных этапов
      # 0, 1 или 2 - запуск тестов для соответствующего этапа
